/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-19 08:30:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Zoo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import co.kh.dev.boardone.model.BoardVO;
import co.kh.dev.boardone.model.BoardDAO;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("co.kh.dev.boardone.model.BoardDAO");
    _jspx_imports_classes.add("co.kh.dev.boardone.model.BoardVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");
int num = Integer.parseInt(request.getParameter("num"));
String pageNum = request.getParameter("pageNum");
BoardVO vo = new BoardVO();
vo.setNum(num);
try {
	BoardDAO bdao = BoardDAO.getInstance();
	BoardVO article = bdao.selectBoardOneDB(vo);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>문정배</title>\r\n");
      out.write("<link href=\"write.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"script.js?timestamp=");
      out.print(System.currentTimeMillis());
      out.write("\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"onload()\">\r\n");
      out.write("	");

	if (id != null) {
	
      out.write("\r\n");
      out.write("	<div class=\"banner\">\r\n");
      out.write("		<div class=\"banner_left\">\r\n");
      out.write("			<a href=\"Zoo.jsp\" target=\"_self\"><i class=\"fa-solid fa-cat\"></i></a>\r\n");
      out.write("			<a href=\"Zoo.jsp\"><p>123</p></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"banner_right\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"dropdown\"><a href=\"#\" class=\"dropdown_button\">매장소개</a>\r\n");
      out.write("					<div class=\"dropdown_content\">\r\n");
      out.write("						<a href=\"#\">관람 유의사항</a> <a href=\"#\">운영시간</a> <a href=\"#\">매장안내</a>\r\n");
      out.write("						<a href=\"#\">오시는길</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("				<li class=\"dropdown\"><a href=\"#\" class=\"dropdown_button\">체험정보</a>\r\n");
      out.write("					<div class=\"dropdown_content\">\r\n");
      out.write("						<a href=\"#\">프로그램 안내</a> <a href=\"#\">동물정보</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("				<li class=\"dropdown\"><a href=\"#\" class=\"dropdown_button\">매장정보</a>\r\n");
      out.write("					<div class=\"dropdown_content\">\r\n");
      out.write("						<a href=\"#\">제휴/할인 안내</a> <a href=\"#\">운영시간</a> <a href=\"#\">매장안내</a>\r\n");
      out.write("						<a href=\"#\">오시는길</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("				<li class=\"dropdown\"><a href=\"list.jsp\" class=\"dropdown_button\">커뮤니티</a>\r\n");
      out.write("					<div class=\"dropdown_content\">\r\n");
      out.write("						<a href=\"list.jsp\">자유게시판</a> <a href=\"#\">자료실</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"input_button\">\r\n");
      out.write("			<button type=\"button\" class=\"ticket\">\r\n");
      out.write("				<i class=\"fa-solid fa-ticket\"></i><span>구매하기</span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<ul class=\"myPage\">\r\n");
      out.write("				<li class=\"dropdown\"><b>");
      out.print(id);
      out.write("</b>님 환영합니다.\r\n");
      out.write("					<div class=\"dropdown_content\">\r\n");
      out.write("						<a href=\"#\">마이페이지</a> <a href=\"./login/logout.jsp\">로그아웃</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<nav>\r\n");
      out.write("			<h4>커뮤니티</h4>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<a href=\"list.jsp\"><li>자유게시판</li></a>\r\n");
      out.write("				<a href=\"\"><li>자료실</li></a>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div class=write_content>\r\n");
      out.write("			<h4 class=\"title\">자유게시판</h4>\r\n");
      out.write("			<div class=\"write\">\r\n");
      out.write("				<form method=\"post\" name=\"writeform\"\r\n");
      out.write("					action=\"updateProc.jsp?pageNum=");
      out.print(pageNum);
      out.write("\" onsubmit=\"\">\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>이 름</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"writer\"\r\n");
      out.write("								value=\"");
      out.print(article.getWriter());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("								name=\"num\" value=\"");
      out.print(article.getNum());
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>제 목</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"subject\"\r\n");
      out.write("								value=\"");
      out.print(article.getSubject());
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>Email</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"email\"\r\n");
      out.write("								value=\"");
      out.print(article.getEmail());
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>내 용</td>\r\n");
      out.write("							<td><textarea name=\"content\" rows=\"13\" cols=\"40\">");
      out.print(article.getContent());
      out.write("</textarea></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>비밀번호</td>\r\n");
      out.write("							<td><input type=\"password\" name=\"pass\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"submit\" value=\"글수정\"> <input\r\n");
      out.write("								type=\"reset\" value=\"다시작성\"> <input type=\"button\"\r\n");
      out.write("								value=\"목록보기\"\r\n");
      out.write("								onclick=\"document.location.href='list.jsp?pageNum=");
      out.print(pageNum);
      out.write("'\">\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</form>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<script>\r\n");
      out.write("					alert(\"로그인 후 이용 바랍니다.\")\r\n");
      out.write("					history.go(-1);\r\n");
      out.write("				</script>\r\n");
      out.write("				");

				}
				} catch (Exception e) {
				}
				
      out.write("\r\n");
      out.write("			\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
